// Load your images on page-load
    function preloader() {
        const imagesPaths = [
           "../img/content/hydro.jpg",
           "../img/content/solar.jpg",
           "../img/content/wind.jpg"
        ];
        const images = [];
        for (let i = 0; i < imagesPaths.length; i++) {
            images[i] = new Image();
            images[i].src = imagesPaths[i];
        }

        // Images ready to be used:
        console.log(`Preloaded images:\n\t${images[0].src}\n\t${images[1].src}\n\t${images[2].src}`);
    };    
    window.addEventListener("load", preloader);
    
    

//getting refference-------------------------------
let $dc = document.getElementById('dynamic-content');


//Nodelist------------------------------------
var nodeList = document.querySelectorAll("button");



//Resources------------------------------------------
const data = {
    partial1: {
        heading: 'Wind Power',
        imageURL: "../img/content/wind.jpg",
        imageAlt: "An image of wind mills",
        bodyText: 'Wind power is generated by harnessing the power wind using turbines and windmills. As the wind makes the turbine blades moves, this in turn makes electrical generators generate electricity. Wind is generally considered to be an affordable eco friendly method of generating electricity. Wind turbines are often an investment at the outset that pays itself off over time and generates a healthy amount of electricity when produced at scale (i.e., many turbines can be fit across large areas). The issue with wind, however, is that turbines often need to be placed in areas that are far from urban areas which can make decisions to invest in wind more complicated. '},
    partial2: {
        heading: 'Solar Power',
        imageURL: "../img/content/solar.jpg",
        imageAlt: "An image of the sun rise over a hill",
        bodyText: 'Solar power is generated by converting sunlight directly into electricity. This method is the cheapest and most reasonable method for the average person to generate their own renewable energy. The price of solar power has dropped dramatically over the past 40 years since the first time a solar grid was created. It is also becoming more and more common for people to install solar panels on their roofs to generate some electricity. The disadvantage to solar power is the sheer number of panels needed to generate electricity. For someone with solar panels on their roof, with the current technology, this would not generate enough to power their house, but would still diminish their reliance upon city grids considerably and thus save them money over time as their panel pays itself off within the first few years.'},
    partial3: {
        heading: 'Hydro Power',
        imageURL: "../img/content/hydro.jpg",
        imageAlt: "An image of a hydro dam",
        bodyText: 'Hydro power is generated most often using dams placed within heavy currents. The dams use the natural force of the rushing water to create movement and power machines to create electricity. Hydro power is generally considered to be a decent eco friendly alternative to fossil fuels as it generally avoids producing carbon emissions. Hydro dams tend to last a long time (At least 50 years) and often require low maintenance over that lifetime, thus making it a very economic solution in the long run. The upfront high cost of hydro is subsidised over its lifetime and ultimately the amount of consistent output produced by hydro makes it one of the best eco friendly power solutions. '},
};

const markup = {
    wind: `<h2>${data.partial1.heading}</h2>
             <img src="${data.partial1.imageURL}" alt="${data.partial1.imageAlt}">
             <p>${data.partial1.bodyText}</p>`,
    solar: `<h2>${data.partial2.heading}</h2>
             <img src="${data.partial2.imageURL}" alt="${data.partial2.imageAlt}">
             <p>${data.partial2.bodyText}</p>`,
    hydro: `<h2>${data.partial3.heading}</h2>
             <img src="${data.partial3.imageURL}" alt="${data.partial3.imageAlt}">
             <p>${data.partial3.bodyText}</p>`,
}


//Initial Page markup----------------------------------
$dc.innerHTML = markup.wind;


//Function handle selector-----------------------------
function handleSelection(ev) {

    let currentButton = ev.target;
    
    for (let i = 0; i < nodeList.length; i++) {

        if (nodeList[i].hasAttribute('id')) {

            nodeList[i].removeAttribute('id');
        }
    }

    currentButton.setAttribute('id', 'active-button');

        if (ev.target == nodeList[0] ) {
            $dc.innerHTML = markup.wind;
        } 

        if (ev.target == nodeList[1] ) {
            $dc.innerHTML = markup.solar;
        } 

        if (ev.target == nodeList[2] ) {
            $dc.innerHTML = markup.hydro;
        } 

}

//registering items for click event-------------------
for (let i = 0; i < nodeList.length; i++) {
    nodeList[i].addEventListener('click', handleSelection);
}
